# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e3382cae5a92e6b09d62ad38d57f1a2079350ac4c15806681351313bb70b77b96ee455d006bd550a17bfdf846d779f0b35d0d85fcd0c1b189ed8c121633dd7d7

test:
  secret_key_base: b8ea2bb06d9bfbb595090231b682289ebed16cbd48e2a977bcd9e5a9aade12ce4c19270399e07edfd75816f2b5f0b38e51d750fbb3e76317b9b7d8a43e63d67e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
